import type { Metadata } from 'next';
import { ServicePage } from '@/components/service-page';
import { APP_CONFIG } from '@/lib/constants';
import { commonInclusions, faqs as commonFaqs } from '@/lib/seo-content';

export const metadata: Metadata = { title:{absolute:'E-commerce App Development Agency ₹9,999 | Digital Thriv'}, description:'Get a D2C website and Android shopping app for ₹9,999, including catalog setup, premium graphics, conversion boosters, payments and logistics.', alternates:{canonical:'/ecommerce-app-development-agency'}, openGraph:{title:'E-commerce Website + Android App Package ₹9,999',description:'Launch connected web and Android shopping experiences with catalog, graphics, payments, logistics and Meta integrations.',url:'/ecommerce-app-development-agency',type:'website'}, twitter:{card:'summary_large_image',title:'E-commerce Website + Android App Package ₹9,999',description:'Connected website and Android commerce app development for D2C brands.'} };
const faqs=[
 {q:'What is included in the ₹9,999 website and app package?',a:'The package includes an ecommerce website, an Android shopping app, the agreed product catalog, premium graphics, conversion-focused elements and the specified payment, logistics and Meta integrations. Platform accounts, publishing charges and paid third-party services are separate unless explicitly included.'},
 {q:'Will you publish the Android app on Google Play?',a:'Google Play publishing must be listed in the written scope. The client normally needs a Google Play Console developer account and must meet Google’s verification, policy and publishing requirements. Approval is controlled by Google and cannot be guaranteed by Digital Thriv.'},
 {q:'Will the website and Android app share products and orders?',a:'They can share catalog and commerce data when the selected technical solution supports synchronization. The platform, synchronization method and any third-party requirements are confirmed before development.'},
 {q:'Is an iPhone app included?',a:'No. The ₹9,999 base package is specifically for a website and Android app. An iOS application is not included unless it is separately specified and quoted.'},
 ...commonFaqs
];
const plans=[{name:'D2C Website + Android App',price:'₹9,999',bestFor:'D2C brands building web and Android sales channels',intro:'Launch an integrated ecommerce website and Android shopping app with synchronized commerce data where supported, premium graphics and conversion-focused store elements.',features:['Complete ecommerce website','Android customer shopping app','Premium graphics and promotional banners','Conversion-focused web and app elements','Brand styling and mobile-responsive website','Store and app testing','Handover guidance',...commonInclusions],note:'The technical app format, synchronization method, Google Play submission, catalog limit and third-party services are confirmed in writing. iOS is not included in the base package.'}];
export default function Page(){const path='/ecommerce-app-development-agency';const schema={'@context':'https://schema.org','@type':'Service',name:'E-commerce Website and Android App Development',serviceType:'Ecommerce app development and website development',description:'Connected ecommerce website and Android shopping app development for D2C brands.',url:`${APP_CONFIG.websiteUrl}${path}`,image:`${APP_CONFIG.websiteUrl}/images/hero-website-app-premium.png`,provider:{'@type':'Organization',name:'Digital Thriv',url:APP_CONFIG.websiteUrl,telephone:APP_CONFIG.contactPhoneE164},areaServed:{'@type':'Country',name:'India'},offers:{'@type':'Offer',price:'9999',priceCurrency:'INR',url:`${APP_CONFIG.websiteUrl}${path}`,availability:'https://schema.org/InStock'}};return <ServicePage path={path} eyebrow="E-commerce app development agency" title="D2C Website + Android Shopping App for ₹9,999" lead="Build a connected web and Android commerce presence with your catalog, premium graphics, conversion boosters and essential payment, logistics and marketing integrations." plans={plans} includedTitle="Website and Android App Deliverables" included={['Ecommerce website','Android shopping app','Agreed catalog setup','Premium graphics','Conversion boosters','Payment integration','Logistics integration','Meta integration','Web and app testing','Handover guidance']} process={['Confirm platform and app format','Build website and catalog','Connect Android app and integrations','Test, hand over and prepare launch']} faqs={faqs} schema={schema} related={[{href:'/shopify-website-development-packages-india',label:'Shopify packages'},{href:'/woocommerce-development-d2c-india',label:'WooCommerce development'},{href:'/ecommerce-growth-conversion-optimization',label:'Improve an existing store'}]} heroImage="/images/hero-website-app-premium.png" heroImageAlt="Connected ecommerce website and Android shopping app with synchronized catalog and delivery integrations"/>}
