import type { Metadata } from 'next';
import { ServicePage } from '@/components/service-page';
import { APP_CONFIG } from '@/lib/constants';
import { commonInclusions, faqs as commonFaqs } from '@/lib/seo-content';

export const metadata: Metadata = { title: { absolute: 'Shopify Website Development Packages India | Digital Thriv' }, description: 'Compare Shopify website development packages in India: dropshipping setup from ₹2,999 or a customized D2C storefront from ₹4,999.', alternates: { canonical: '/shopify-website-development-packages-india' }, openGraph:{title:'Shopify Website Development Packages India From ₹2,999',description:'Template-based dropshipping stores or customized D2C storefronts with catalog, supplier, payment, logistics and Meta integrations.',url:'/shopify-website-development-packages-india',type:'website'}, twitter:{card:'summary_large_image',title:'Shopify Website Development Packages India From ₹2,999',description:'Dropshipping and customized D2C Shopify packages with integrations and clear written scope.'} };
const faqs = [
  { q:'Do you offer affordable dropshipping store setup services?', a:'Yes. The ₹2,999 Shopify package is our affordable dropshipping store setup service for product testing and early-stage sellers. It includes a premium template-based theme, agreed catalog upload, essential store setup, compatible dropshipping supplier integration, payments, logistics and Meta integration within the written scope.' },
  { q:'Which dropshipping suppliers can you integrate?', a:'We can connect a dropshipping supplier when it provides a compatible Shopify app, supported feed or documented integration method. Supplier accounts, subscriptions, product data access and third-party charges remain the client’s responsibility unless the quotation states otherwise.' },
  { q:'What is the difference between the ₹2,999 and ₹4,999 Shopify packages?', a:'The ₹2,999 package is a template-based Shopify setup for dropshippers who need an affordable launch. The ₹4,999 package is for D2C and ecommerce brands that need higher customization, premium graphics, stronger branding and more conversion-focused sections.' },
  { q:'Is the ₹2,999 Shopify website custom designed?', a:'It is professionally configured using a premium theme and an established template structure. We adapt the branding, products, content and agreed integrations, but extensive layout changes, custom-coded sections and advanced custom graphics are outside the base scope.' },
  { q:'What are conversion boosters?', a:'Depending on platform capabilities, they may include trust indicators, benefit sections, promotional banners, stronger calls to action, reassurance content, offer displays, cross-sell elements and an improved product-page structure. Exact elements are listed in your written scope.' },
  ...commonFaqs
];
const plans = [
 { id:'dropshipping', name:'Shopify Dropshipping Starter', price:'₹2,999', bestFor:'New dropshippers and product testing', intro:'Launch quickly with a professionally configured, template-based Shopify store using a premium theme adapted to your products and brand details.', features:['Complete Shopify setup','Premium template-based theme','Dropshipping supplier integration','Logo, colors and basic branding placement','Essential store pages',...commonInclusions], note:'Template-based package: extensive layout redesign, custom-coded sections and advanced custom graphics are not included.' },
 { id:'d2c', name:'Customized Shopify D2C Store', price:'₹4,999', bestFor:'D2C founders and established ecommerce sellers', intro:'Build a more differentiated Shopify storefront with higher customization, premium visual assets and conversion-focused sections designed around your product and brand.', features:['Higher theme customization','Premium banners and promotional graphics','Conversion-focused product sections','Trust and reassurance elements','Promotional, cross-sell or upsell configuration where supported',...commonInclusions] }
];
export default function Page(){const path='/shopify-website-development-packages-india';const schema={'@context':'https://schema.org','@type':'Service',name:'Shopify Website Development Packages India',serviceType:'Shopify website development and dropshipping store setup',description:'Template-based Shopify dropshipping stores and customized D2C storefronts with catalog and commerce integrations.',url:`${APP_CONFIG.websiteUrl}${path}`,image:`${APP_CONFIG.websiteUrl}/images/hero-d2c-premium.png`,provider:{'@type':'Organization',name:'Digital Thriv',url:APP_CONFIG.websiteUrl,telephone:APP_CONFIG.contactPhoneE164},areaServed:{'@type':'Country',name:'India'},offers:plans.map(p=>({'@type':'Offer',price:p.price.replace(/[₹,]/g,''),priceCurrency:'INR',name:p.name,url:`${APP_CONFIG.websiteUrl}${path}#${p.id}`,availability:'https://schema.org/InStock'}))};return <ServicePage path={path} eyebrow="Shopify website development packages in India" title="Shopify Stores for Dropshippers and D2C Brands" lead="Choose a template-based dropshipping launch from ₹2,999 or a more customized, conversion-focused Shopify storefront from ₹4,999." plans={plans} includedTitle="Shopify Store Setup Inclusions" included={['Premium theme configuration','Agreed catalog upload','Payment gateway setup','Shipping and logistics setup','Meta Pixel and ad integration','Policy and essential page setup','Responsive layout checks','Checkout-flow testing']} process={['Confirm products and scope','Configure theme and catalog','Connect and test integrations','Review, handover and launch']} faqs={faqs} schema={schema} related={[{href:'/woocommerce-development-d2c-india',label:'WooCommerce development'},{href:'/ecommerce-app-development-agency',label:'Website + Android app'},{href:'/ecommerce-growth-conversion-optimization',label:'Improve an existing store'}]} heroImage="/images/hero-d2c-premium.png" heroImageAlt="Premium customized D2C ecommerce storefront displayed across desktop and mobile"/>}
